### ISSUE TITLE
Issue: Alert developer if requirements path is invalid

### ISSUE THREAD

**Issue by pdiazvargas** [eabglobal/juniper#15]
## Actual
As a developer if the path I defined in my manifest file does not exist, notify me! Right now `juni build` is creating an empty folder in the .zip artifact that has nothing. Assume that `lambda/requirements.txt` does not exist. The following manifest definition creates an empty requirements folder.

``` yaml
functions:
  events:
    requirements: ./lambda/requirements.txt
    include:
    - ./lambda/lambda_handler.py
```

## Expected
In the case above as a developer I expected either a warning or an error from juniper letting me know that the path I set for the requirements is not valid.
