### ISSUE TITLE
Requirements definition should be optional

### ISSUE THREAD

**Issue by pdiazvargas** [eabglobal/juniper#19]
## Actual
If the requirements field is not defined in the manifest, when I execute `juni build` the process is failing with the following exeption: `KeyError: 'requirements' `

This is the sample definition

``` yaml
functions:
  sns-to-slack:
    include:
      - ./src/sns-to-slack
```

## Expected
If the function does not define a requirements file, `juni build` should not fail. However, then the field is defined, the validation of the file's existence should be executed
