### ISSUE TITLE
Support Lambda Layers

### ISSUE THREAD

**Issue by pdiazvargas** [eabglobal/juniper#38]
## What
Enhance juniper to support the build of aws lambda layers. Layers are a new concept in the AWS ecosystem that facilitates the pre build/package of dependencies for several lambda functions. The main advantage of this feature is that a lambda function would not longer need to include all of its dependencies in it's zip artifact as long as it references a pre-built layer.

The main enhancement proposal is to support a new section in the manifest that looks as follows: 

``` yaml
functions:
  users:
    include:
    - ./first/get_api.py

layers:
  core:
    requirements: ./requirements/core_layer.txt
  postgres:
    requirements: ./requirements/pg_layer.txt
```

As seen in the example above, the new section does *not* require a includes section. Also, notice that since juniper is used only for building purposes, the `users` function has absolutely no reference to any layer. The wiring of a layer to the function itself happens outside of juniper.

Juniper's responsibility is to create the artifact.

## Resources
https://docs.aws.amazon.com/lambda/latest/dg/configuration-layers.html
