### ISSUE TITLE
Using a custom PyPi server with juniper

### ISSUE THREAD

**Issue by mcouthon** [eabglobal/juniper#40]
Hi, 
We have a custom PyPi server, which I think is ignored by Juniper, when trying to install pip requirements. Is there a way to set the pip `index-url` somewhere in the manifest file?

**Comment by mcouthon** [comment]
Adding `--index-url INDEX_URL` inside `artifacts/package.sh` does the trick, so I think it's only a matter of propagating the value down there.

**Comment by pdiazvargas** [comment]
Hey @mcouthon,
Definitely a use case that I had not come across, but something that juniper needs to support. Given the many parameters that one can use while working with pip, I think a more generic solution will be to support the definition of a [pip.ini](https://pip.pypa.io/en/stable/user_guide/#config-file) file.

What I'm thinking about at the moment would be a global sort of configuration like:

``` yaml
    global:
        pipini: ./config/pip.ini

    functions:
      function1:
        requirements: ./requirements.txt.
        include:
            - ./func1/lambda_function.py
```

Then in the pip.ini file you can define the parameters that you want to like this:

```
[global]
timeout = 60
index-url = https://download.zope.org/ppix
```

Does an approach like this make sense to you?

**Comment by pdiazvargas** [comment]
Hey @mcouthon,
Definitely a use case that I had not come across, but something that juniper needs to support. Given the many parameters that one can use while working with pip, I think a more generic solution will be to support the definition of a [pip.ini](https://pip.pypa.io/en/stable/user_guide/#config-file) file.

What I'm thinking about at the moment would be a global sort of configuration like:

``` yaml
    global:
        pipini: ./config/pip.ini

    functions:
      function1:
        requirements: ./requirements.txt.
        include:
            - ./func1/lambda_function.py
```

Then in the pip.ini file you can define the parameters that you want to like this:

```
[global]
timeout = 60
index-url = https://download.zope.org/ppix
```

Does an approach like this make sense to you?
